root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/user-service"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500

[log]
  time = true
  time_format = "2006-01-02 15:04:05"

[watch]
  # Watch all Go files in the project
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[run]
  cmd = "./tmp/main"