version: '3.9'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

networks: 
  app-network:
    driver: bridge
